from setuptools import setup, find_packages

setup(
    name="secure_stream",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "fastapi==0.104.1",
        "uvicorn==0.24.0",
        "python-multipart==0.0.6",
        "web3==6.11.1",
        "tensorflow==2.14.0",
        "opencv-python==4.8.1.78",
        "numpy==1.24.3",
        "pycryptodome==3.19.0",
        "python-jose==3.3.0",
        "sqlalchemy==2.0.23",
        "pydantic==2.4.2",
        "python-dotenv==1.0.0",
        "requests==2.31.0",
        "pillow==10.1.0",
        "eth-typing==3.5.2"
    ],
    python_requires=">=3.8",
    author="Your Name",
    author_email="your.email@example.com",
    description="SecureStream - Anti-Piracy Solution",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/yourusername/securestream",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
)
